### Ver bancos

GET http://localhost:8080/api/bancos HTTP/1.1

### Obtener un banco

# @prompt bancoId

GET http://localhost:8080/api/bancos/{{bancoId}} HTTP/1.1

### Crear banco

POST http://localhost:8080/api/bancos HTTP/1.1
content-type: application/json

{
  "difficulty": "difisi",
  "address": "C/ Nose, 123",
  "available": true,
  "image": "312.png",
  "name": "Nose",
  "reward": 2
}

### Crear varios bancos

POST http://localhost:8080/api/bancos HTTP/1.1
content-type: application/json

[
  {
    "difficulty": "fasi",
    "address": "C/ Nose, 321",
    "available": true,
    "image": "312.png",
    "name": "Nose",
    "reward": 3
  },
  {
    "difficulty": "difisi",
    "address": "C/ Nose, 123",
    "available": true,
    "image": "312.png",
    "name": "Nose",
    "reward": 31
  }
]

### Actualizar un banco

# @prompt bancoId

PUT http://localhost:8080/api/bancos/{{bancoId}} HTTP/1.1
content-type: application/json

{
  "difficulty": "medio",
  "address": "C/ Sise, 321",
  "available": true,
  "image": "pn jeje",
  "name": "looooool",
  "reward": 1231
}

### Eliminar todos los bancos

DELETE http://localhost:8080/api/bancos HTTP/1.1

### Eliminar un banco

# @prompt bancoId

DELETE http://localhost:8080/api/bancos/{{bancoId}} HTTP/1.1
